---

- name: Nginx | Ensure conf.d, sites-available, and sites-enabled directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx_confd_directory }}"
    - "{{ nginx_sites_available_directory }}"
    - "{{ nginx_sites_enabled_directory }}"
  notify: reload nginx

- name: Nginx | Remove default nginx serverblock 
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_installed.changed 
  notify:
    - restart nginx

- name: Nginx | Copy .conf files into conf.d directory
  template:
    src: "{{ item }}"
    dest: "{{ nginx_confd_directory }}/{{ item | basename }}"
    owner: "{{ nginx_user }}"
    mode: 0644
  with_items: "{{ nginx_confd_files }}"
  notify:
    - validate nginx configuration
    - restart nginx

- name: Nginx | Copy serverblock files into sites-available directory
  template:
    src: "{{ item }}"
    dest: "{{ nginx_sites_available_directory }}/{{ item | basename }}"
    owner: "{{ nginx_user }}"
    mode: 0644
  with_items: "{{ nginx_sites_available_files }}"
  notify:
    - validate nginx configuration
    - restart nginx

- name: Nginx | Find all files in sites-available directory
  find:
    path: "{{ nginx_sites_available_directory }}"
    file_type: any
  register: sites_available_result

- name: Nginx | Symlink files in sites-available directory to sites-enabled directory
  file:
    src: "{{ nginx_sites_available_directory }}/{{ item.path | basename }}"
    dest: "{{ nginx_sites_enabled_directory }}/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ sites_available_result.files }}"
  when: item.path | basename != 'default'

- name: Nginx | Copy nginx.conf in place
  template:
    src: nginx.conf
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: root
    mode: 0644
    validate: nginx -t -c %s 
  notify: reload nginx