---

- name: Add PPA for Nginx
  apt_repository:
    repo: "ppa:nginx/{{ nginx_ppa_version }}"
    state: present
    update_cache: yes
  register: nginx_ppa_added
  # when: nginx_ppa_use

- name: Ensure Nginx will reinstall if the PPA was just added
  apt:
    name: nginx
    state: absent
  when: nginx_ppa_added.changed

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  changed_when: false

- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: installed