---

- import_tasks: dhparams.yml
  tags:
    - nginx
    - nginx_dhparams

- import_tasks: install.yml
  tags:
    - nginx
    - nginx_install

- import_tasks: configure.yml
  tags: 
    - nginx
    - nginx_configure

- name: Nginx | Ensure nginx is started and enabled to start at boot.
  service: 
    name: nginx 
    state: started 
    enabled: yes